---
- name: "Ensure nginx servers are running on all hosts."
  hosts: all
  remote_user: rbisewski

  tasks:
    - name: "sudo systemctl start nginx"
      service:
        name: nginx
        state: started
      become: yes
      become_method: sudo
